# Generated by Django 4.2 on 2023-06-08 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminpanelProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_nm', models.CharField(max_length=20)),
                ('emp_id', models.CharField(max_length=30)),
                ('emp_mob', models.IntegerField()),
                ('emp_pass', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='foods',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('fimg', models.ImageField(max_length=255, null=True, upload_to='')),
                ('avail', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('f_rate', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('sid', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('o_active', models.IntegerField(default=0)),
                ('t_active', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('oname', models.CharField(default='NO NAME', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('sphone', models.CharField(max_length=10, unique=True)),
                ('sadd', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=16, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('fssai_no', models.CharField(max_length=14, unique=True)),
                ('baccno', models.CharField(max_length=16)),
                ('ifsc', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('verification', models.IntegerField(default=0)),
                ('o_active', models.IntegerField(default=0)),
                ('t_active', models.IntegerField(default=0)),
                ('rest_img', models.ImageField(max_length=255, null=True, upload_to='')),
                ('r_rate', models.CharField(max_length=5, null=True)),
                ('total_purchased', models.IntegerField(default=0)),
                ('last_login', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('cimg', models.ImageField(max_length=255, null=True, upload_to='')),
                ('total_purchased', models.IntegerField(default=0)),
                ('last_login', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('fid', models.IntegerField()),
                ('sid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_cart_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
